/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CaseStatusRouteImport } from './routes/case-status'
import { Route as SetupAdminRouteImport } from './routes/setup-admin'
import { Route as AuthenticatedActivityLogRouteImport } from './routes/_authenticated/activity-log'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBacklogSimulatorRouteImport } from './routes/_authenticated/backlog-simulator'
import { Route as AuthenticatedBenchRouteImport } from './routes/_authenticated/bench'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCauseListRouteImport } from './routes/_authenticated/cause-list'
import { Route as AuthenticatedConflictsRouteImport } from './routes/_authenticated/conflicts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGovernanceRouteImport } from './routes/_authenticated/governance'
import { Route as AuthenticatedPrioritySettingsRouteImport } from './routes/_authenticated/priority-settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSmartSchedulingRouteImport } from './routes/_authenticated/smart-scheduling'
import { Route as AuthenticatedWhatIfSimulationRouteImport } from './routes/_authenticated/what-if-simulation'
import { Route as AuthenticatedAssetsIndexRouteImport } from './routes/_authenticated/assets/index'
import { Route as AuthenticatedAssetsAssetIdRouteImport } from './routes/_authenticated/assets/$assetId'
import { Route as AuthenticatedAssetsNewRouteImport } from './routes/_authenticated/assets/new'
import { Route as AuthenticatedCasesIndexRouteImport } from './routes/_authenticated/cases/index'
import { Route as AuthenticatedCasesCaseIdRouteImport } from './routes/_authenticated/cases/$caseId'
import { Route as AuthenticatedCasesNewRouteImport } from './routes/_authenticated/cases/new'
import { Route as AuthenticatedCourtroomsIndexRouteImport } from './routes/_authenticated/courtrooms/index'
import { Route as AuthenticatedCourtroomsCourtroomIdRouteImport } from './routes/_authenticated/courtrooms/$courtroomId'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents/index'
import { Route as AuthenticatedDocumentsDocumentIdRouteImport } from './routes/_authenticated/documents/$documentId'
import { Route as AuthenticatedJudgesIndexRouteImport } from './routes/_authenticated/judges/index'
import { Route as AuthenticatedJudgesJudgeIdRouteImport } from './routes/_authenticated/judges/$judgeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStatusRoute = CaseStatusRouteImport.update({
  id: '/case-status',
  path: '/case-status',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAdminRoute = SetupAdminRouteImport.update({
  id: '/setup-admin',
  path: '/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityLogRoute =
  AuthenticatedActivityLogRouteImport.update({
    id: '/activity-log',
    path: '/activity-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBacklogSimulatorRoute =
  AuthenticatedBacklogSimulatorRouteImport.update({
    id: '/backlog-simulator',
    path: '/backlog-simulator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBenchRoute = AuthenticatedBenchRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCauseListRoute = AuthenticatedCauseListRouteImport.update({
  id: '/cause-list',
  path: '/cause-list',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConflictsRoute = AuthenticatedConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGovernanceRoute = AuthenticatedGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrioritySettingsRoute =
  AuthenticatedPrioritySettingsRouteImport.update({
    id: '/priority-settings',
    path: '/priority-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSmartSchedulingRoute =
  AuthenticatedSmartSchedulingRouteImport.update({
    id: '/smart-scheduling',
    path: '/smart-scheduling',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatIfSimulationRoute =
  AuthenticatedWhatIfSimulationRouteImport.update({
    id: '/what-if-simulation',
    path: '/what-if-simulation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsIndexRoute =
  AuthenticatedAssetsIndexRouteImport.update({
    id: '/assets/',
    path: '/assets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsAssetIdRoute =
  AuthenticatedAssetsAssetIdRouteImport.update({
    id: '/assets/$assetId',
    path: '/assets/$assetId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsNewRoute = AuthenticatedAssetsNewRouteImport.update({
  id: '/assets/new',
  path: '/assets/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesIndexRoute = AuthenticatedCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesCaseIdRoute =
  AuthenticatedCasesCaseIdRouteImport.update({
    id: '/cases/$caseId',
    path: '/cases/$caseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCasesNewRoute = AuthenticatedCasesNewRouteImport.update({
  id: '/cases/new',
  path: '/cases/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCourtroomsIndexRoute =
  AuthenticatedCourtroomsIndexRouteImport.update({
    id: '/courtrooms/',
    path: '/courtrooms/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCourtroomsCourtroomIdRoute =
  AuthenticatedCourtroomsCourtroomIdRouteImport.update({
    id: '/courtrooms/$courtroomId',
    path: '/courtrooms/$courtroomId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsDocumentIdRoute =
  AuthenticatedDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJudgesIndexRoute =
  AuthenticatedJudgesIndexRouteImport.update({
    id: '/judges/',
    path: '/judges/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJudgesJudgeIdRoute =
  AuthenticatedJudgesJudgeIdRouteImport.update({
    id: '/judges/$judgeId',
    path: '/judges/$judgeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/case-status': typeof CaseStatusRoute
  '/setup-admin': typeof SetupAdminRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/backlog-simulator': typeof AuthenticatedBacklogSimulatorRoute
  '/bench': typeof AuthenticatedBenchRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/cause-list': typeof AuthenticatedCauseListRoute
  '/conflicts': typeof AuthenticatedConflictsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/priority-settings': typeof AuthenticatedPrioritySettingsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/smart-scheduling': typeof AuthenticatedSmartSchedulingRoute
  '/what-if-simulation': typeof AuthenticatedWhatIfSimulationRoute
  '/assets/$assetId': typeof AuthenticatedAssetsAssetIdRoute
  '/assets/new': typeof AuthenticatedAssetsNewRoute
  '/cases/$caseId': typeof AuthenticatedCasesCaseIdRoute
  '/cases/new': typeof AuthenticatedCasesNewRoute
  '/courtrooms/$courtroomId': typeof AuthenticatedCourtroomsCourtroomIdRoute
  '/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/judges/$judgeId': typeof AuthenticatedJudgesJudgeIdRoute
  '/assets/': typeof AuthenticatedAssetsIndexRoute
  '/cases/': typeof AuthenticatedCasesIndexRoute
  '/courtrooms/': typeof AuthenticatedCourtroomsIndexRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/judges/': typeof AuthenticatedJudgesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/case-status': typeof CaseStatusRoute
  '/setup-admin': typeof SetupAdminRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/backlog-simulator': typeof AuthenticatedBacklogSimulatorRoute
  '/bench': typeof AuthenticatedBenchRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/cause-list': typeof AuthenticatedCauseListRoute
  '/conflicts': typeof AuthenticatedConflictsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/priority-settings': typeof AuthenticatedPrioritySettingsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/smart-scheduling': typeof AuthenticatedSmartSchedulingRoute
  '/what-if-simulation': typeof AuthenticatedWhatIfSimulationRoute
  '/assets/$assetId': typeof AuthenticatedAssetsAssetIdRoute
  '/assets/new': typeof AuthenticatedAssetsNewRoute
  '/cases/$caseId': typeof AuthenticatedCasesCaseIdRoute
  '/cases/new': typeof AuthenticatedCasesNewRoute
  '/courtrooms/$courtroomId': typeof AuthenticatedCourtroomsCourtroomIdRoute
  '/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/judges/$judgeId': typeof AuthenticatedJudgesJudgeIdRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/cases': typeof AuthenticatedCasesIndexRoute
  '/courtrooms': typeof AuthenticatedCourtroomsIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/judges': typeof AuthenticatedJudgesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/case-status': typeof CaseStatusRoute
  '/setup-admin': typeof SetupAdminRoute
  '/_authenticated/activity-log': typeof AuthenticatedActivityLogRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/backlog-simulator': typeof AuthenticatedBacklogSimulatorRoute
  '/_authenticated/bench': typeof AuthenticatedBenchRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/cause-list': typeof AuthenticatedCauseListRoute
  '/_authenticated/conflicts': typeof AuthenticatedConflictsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/governance': typeof AuthenticatedGovernanceRoute
  '/_authenticated/priority-settings': typeof AuthenticatedPrioritySettingsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/smart-scheduling': typeof AuthenticatedSmartSchedulingRoute
  '/_authenticated/what-if-simulation': typeof AuthenticatedWhatIfSimulationRoute
  '/_authenticated/assets/$assetId': typeof AuthenticatedAssetsAssetIdRoute
  '/_authenticated/assets/new': typeof AuthenticatedAssetsNewRoute
  '/_authenticated/cases/$caseId': typeof AuthenticatedCasesCaseIdRoute
  '/_authenticated/cases/new': typeof AuthenticatedCasesNewRoute
  '/_authenticated/courtrooms/$courtroomId': typeof AuthenticatedCourtroomsCourtroomIdRoute
  '/_authenticated/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/_authenticated/judges/$judgeId': typeof AuthenticatedJudgesJudgeIdRoute
  '/_authenticated/assets/': typeof AuthenticatedAssetsIndexRoute
  '/_authenticated/cases/': typeof AuthenticatedCasesIndexRoute
  '/_authenticated/courtrooms/': typeof AuthenticatedCourtroomsIndexRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/judges/': typeof AuthenticatedJudgesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/case-status'
    | '/setup-admin'
    | '/activity-log'
    | '/admin'
    | '/backlog-simulator'
    | '/bench'
    | '/calendar'
    | '/cause-list'
    | '/conflicts'
    | '/dashboard'
    | '/governance'
    | '/priority-settings'
    | '/reports'
    | '/search'
    | '/smart-scheduling'
    | '/what-if-simulation'
    | '/assets/$assetId'
    | '/assets/new'
    | '/cases/$caseId'
    | '/cases/new'
    | '/courtrooms/$courtroomId'
    | '/documents/$documentId'
    | '/judges/$judgeId'
    | '/assets/'
    | '/cases/'
    | '/courtrooms/'
    | '/documents/'
    | '/judges/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/case-status'
    | '/setup-admin'
    | '/activity-log'
    | '/admin'
    | '/backlog-simulator'
    | '/bench'
    | '/calendar'
    | '/cause-list'
    | '/conflicts'
    | '/dashboard'
    | '/governance'
    | '/priority-settings'
    | '/reports'
    | '/search'
    | '/smart-scheduling'
    | '/what-if-simulation'
    | '/assets/$assetId'
    | '/assets/new'
    | '/cases/$caseId'
    | '/cases/new'
    | '/courtrooms/$courtroomId'
    | '/documents/$documentId'
    | '/judges/$judgeId'
    | '/assets'
    | '/cases'
    | '/courtrooms'
    | '/documents'
    | '/judges'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/case-status'
    | '/setup-admin'
    | '/_authenticated/activity-log'
    | '/_authenticated/admin'
    | '/_authenticated/backlog-simulator'
    | '/_authenticated/bench'
    | '/_authenticated/calendar'
    | '/_authenticated/cause-list'
    | '/_authenticated/conflicts'
    | '/_authenticated/dashboard'
    | '/_authenticated/governance'
    | '/_authenticated/priority-settings'
    | '/_authenticated/reports'
    | '/_authenticated/search'
    | '/_authenticated/smart-scheduling'
    | '/_authenticated/what-if-simulation'
    | '/_authenticated/assets/$assetId'
    | '/_authenticated/assets/new'
    | '/_authenticated/cases/$caseId'
    | '/_authenticated/cases/new'
    | '/_authenticated/courtrooms/$courtroomId'
    | '/_authenticated/documents/$documentId'
    | '/_authenticated/judges/$judgeId'
    | '/_authenticated/assets/'
    | '/_authenticated/cases/'
    | '/_authenticated/courtrooms/'
    | '/_authenticated/documents/'
    | '/_authenticated/judges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CaseStatusRoute: typeof CaseStatusRoute
  SetupAdminRoute: typeof SetupAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-status': {
      id: '/case-status'
      path: '/case-status'
      fullPath: '/case-status'
      preLoaderRoute: typeof CaseStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-admin': {
      id: '/setup-admin'
      path: '/setup-admin'
      fullPath: '/setup-admin'
      preLoaderRoute: typeof SetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity-log': {
      id: '/_authenticated/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof AuthenticatedActivityLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backlog-simulator': {
      id: '/_authenticated/backlog-simulator'
      path: '/backlog-simulator'
      fullPath: '/backlog-simulator'
      preLoaderRoute: typeof AuthenticatedBacklogSimulatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bench': {
      id: '/_authenticated/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof AuthenticatedBenchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cause-list': {
      id: '/_authenticated/cause-list'
      path: '/cause-list'
      fullPath: '/cause-list'
      preLoaderRoute: typeof AuthenticatedCauseListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conflicts': {
      id: '/_authenticated/conflicts'
      path: '/conflicts'
      fullPath: '/conflicts'
      preLoaderRoute: typeof AuthenticatedConflictsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance': {
      id: '/_authenticated/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AuthenticatedGovernanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/priority-settings': {
      id: '/_authenticated/priority-settings'
      path: '/priority-settings'
      fullPath: '/priority-settings'
      preLoaderRoute: typeof AuthenticatedPrioritySettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/smart-scheduling': {
      id: '/_authenticated/smart-scheduling'
      path: '/smart-scheduling'
      fullPath: '/smart-scheduling'
      preLoaderRoute: typeof AuthenticatedSmartSchedulingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/what-if-simulation': {
      id: '/_authenticated/what-if-simulation'
      path: '/what-if-simulation'
      fullPath: '/what-if-simulation'
      preLoaderRoute: typeof AuthenticatedWhatIfSimulationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets/': {
      id: '/_authenticated/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthenticatedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets/$assetId': {
      id: '/_authenticated/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AuthenticatedAssetsAssetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets/new': {
      id: '/_authenticated/assets/new'
      path: '/assets/new'
      fullPath: '/assets/new'
      preLoaderRoute: typeof AuthenticatedAssetsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases/': {
      id: '/_authenticated/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AuthenticatedCasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases/$caseId': {
      id: '/_authenticated/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases/new': {
      id: '/_authenticated/cases/new'
      path: '/cases/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof AuthenticatedCasesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courtrooms/': {
      id: '/_authenticated/courtrooms/'
      path: '/courtrooms'
      fullPath: '/courtrooms/'
      preLoaderRoute: typeof AuthenticatedCourtroomsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courtrooms/$courtroomId': {
      id: '/_authenticated/courtrooms/$courtroomId'
      path: '/courtrooms/$courtroomId'
      fullPath: '/courtrooms/$courtroomId'
      preLoaderRoute: typeof AuthenticatedCourtroomsCourtroomIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$documentId': {
      id: '/_authenticated/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/judges/': {
      id: '/_authenticated/judges/'
      path: '/judges'
      fullPath: '/judges/'
      preLoaderRoute: typeof AuthenticatedJudgesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/judges/$judgeId': {
      id: '/_authenticated/judges/$judgeId'
      path: '/judges/$judgeId'
      fullPath: '/judges/$judgeId'
      preLoaderRoute: typeof AuthenticatedJudgesJudgeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityLogRoute: typeof AuthenticatedActivityLogRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBacklogSimulatorRoute: typeof AuthenticatedBacklogSimulatorRoute
  AuthenticatedBenchRoute: typeof AuthenticatedBenchRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCauseListRoute: typeof AuthenticatedCauseListRoute
  AuthenticatedConflictsRoute: typeof AuthenticatedConflictsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGovernanceRoute: typeof AuthenticatedGovernanceRoute
  AuthenticatedPrioritySettingsRoute: typeof AuthenticatedPrioritySettingsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSmartSchedulingRoute: typeof AuthenticatedSmartSchedulingRoute
  AuthenticatedWhatIfSimulationRoute: typeof AuthenticatedWhatIfSimulationRoute
  AuthenticatedAssetsAssetIdRoute: typeof AuthenticatedAssetsAssetIdRoute
  AuthenticatedAssetsNewRoute: typeof AuthenticatedAssetsNewRoute
  AuthenticatedCasesCaseIdRoute: typeof AuthenticatedCasesCaseIdRoute
  AuthenticatedCasesNewRoute: typeof AuthenticatedCasesNewRoute
  AuthenticatedCourtroomsCourtroomIdRoute: typeof AuthenticatedCourtroomsCourtroomIdRoute
  AuthenticatedDocumentsDocumentIdRoute: typeof AuthenticatedDocumentsDocumentIdRoute
  AuthenticatedJudgesJudgeIdRoute: typeof AuthenticatedJudgesJudgeIdRoute
  AuthenticatedAssetsIndexRoute: typeof AuthenticatedAssetsIndexRoute
  AuthenticatedCasesIndexRoute: typeof AuthenticatedCasesIndexRoute
  AuthenticatedCourtroomsIndexRoute: typeof AuthenticatedCourtroomsIndexRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedJudgesIndexRoute: typeof AuthenticatedJudgesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityLogRoute: AuthenticatedActivityLogRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBacklogSimulatorRoute: AuthenticatedBacklogSimulatorRoute,
  AuthenticatedBenchRoute: AuthenticatedBenchRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCauseListRoute: AuthenticatedCauseListRoute,
  AuthenticatedConflictsRoute: AuthenticatedConflictsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGovernanceRoute: AuthenticatedGovernanceRoute,
  AuthenticatedPrioritySettingsRoute: AuthenticatedPrioritySettingsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSmartSchedulingRoute: AuthenticatedSmartSchedulingRoute,
  AuthenticatedWhatIfSimulationRoute: AuthenticatedWhatIfSimulationRoute,
  AuthenticatedAssetsAssetIdRoute: AuthenticatedAssetsAssetIdRoute,
  AuthenticatedAssetsNewRoute: AuthenticatedAssetsNewRoute,
  AuthenticatedCasesCaseIdRoute: AuthenticatedCasesCaseIdRoute,
  AuthenticatedCasesNewRoute: AuthenticatedCasesNewRoute,
  AuthenticatedCourtroomsCourtroomIdRoute:
    AuthenticatedCourtroomsCourtroomIdRoute,
  AuthenticatedDocumentsDocumentIdRoute: AuthenticatedDocumentsDocumentIdRoute,
  AuthenticatedJudgesJudgeIdRoute: AuthenticatedJudgesJudgeIdRoute,
  AuthenticatedAssetsIndexRoute: AuthenticatedAssetsIndexRoute,
  AuthenticatedCasesIndexRoute: AuthenticatedCasesIndexRoute,
  AuthenticatedCourtroomsIndexRoute: AuthenticatedCourtroomsIndexRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  AuthenticatedJudgesIndexRoute: AuthenticatedJudgesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CaseStatusRoute: CaseStatusRoute,
  SetupAdminRoute: SetupAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
